; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Original board config file from: https://github.com/UnsignedArduino/ESP32-S3-Super-Mini-Test
; https://community.platformio.org/t/esp32-s3-zero-does-not-work-on-platformio/40297/10?u=unsignedarduino
; https://github.com/sivar2311/ESP32-S3-PlatformIO-Flash-and-PSRAM-configurations
; https://github.com/pioarduino/platform-espressif32/blob/main/examples/tasmota_platformio_override.ini

;in order to get to the menuconfig: 
;   open the terminal, type -> start
;   it will open an individual terminal window, so that the terminal UI works correctly
;   then type -> pio run -t menuconfig
;   !!! DOESNT WORK WITH HYBRID COMPILE !!!
;
[platformio]
default_envs = esp32-s3-SuperMini

[env:esp32-s3-SuperMini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-supermini
framework = arduino
board_build.filesystem = littlefs ; LittleFS setup
board_build.partitions = no_ota.csv
debug_tool = esp-builtin

monitor_speed = 512000
monitor_filters = esp32_exception_decoder

build_flags = 
    ;-Wall -Wextra
    -Wno-deprecated-declarations
    -O2                         ; 
    ;-DCORE_DEBUG_LEVEL=0       ; NONE - No log output. Used to completely disable logging 
                                ;   (lowest impact on output)
    ;-DCORE_DEBUG_LEVEL=1       ; ERROR - Critical errors indicating that the software 
                                ;   cannot recover without intervention
    ;-DCORE_DEBUG_LEVEL=2       ; WARNING - Events that could potentially cause issues but 
                                ;   have been handled or mitigated
    ;-DCORE_DEBUG_LEVEL=3       ; INFO - General information messages that describe the 
                                ;   normal operation of the system
    -DCORE_DEBUG_LEVEL=4       ; DEBUG - Detailed diagnostic messages intended to aid in
                                ;   debugging (e.g., variable values, pointer addresses)
    ;-DCORE_DEBUG_LEVEL=5        ; VERBOSE - Highly detailed and frequent debugging messages,
                                ;   often including internal states, that may overwhelm the 
                                ;   output (highest impact on output)
    -DHTTPCLIENT_NOSECURE
    -DUPDATE_NOCRYPT

lib_ignore =
    Micro-RTSP  ; Provides RTSP (Real-Time Streaming Protocol) server support for video streaming 
                ;   (e.g., from ESP32-CAM)
    epdiy       ; Driver for E-Paper (e-ink) displays

    ;Bluetooth
    ;BLE
    BluetoothSerial
    SimpleBLE

    WiFiProv    ; Espressif’s Wi-Fi setup helper (uses BLE/SoftAP). Part of their provisioning apps
    ESP_I2S     ; Espressif’s I2S audio interface (used for microphones, DACs, speakers)
    ESP_NOW     ; Espressif’s peer-to-peer Wi-Fi communication protocol
    ESP_SR      ; Espressif’s voice recognition library
    RainMaker   ; Espressif’s RainMaker cloud platform
    Insights    ; Espressif’s cloud diagnostics/analytics
    
    ;SPIFFS
    ;USB

    ;IoT protocols
    Matter
    OpenThread
    NetworkClientSecure 
    Zigbee

custom_component_remove =
    ;espressif/fb_gfx                    ;Some Espressif’s GFX library of some sort
    espressif/esp_modem                 ;Espressif’s ommunication with GSM/LTE modems protocols

    ;Espressif’s Zigbee IoT protocols
    espressif/esp-zboss-lib
    espressif/esp-zigbee-lib

    ;Espressif’s rainmaker cloud IoT platform protocols
    espressif/esp_rainmaker
    espressif/rmaker_common

    ;Espressif’s Wi-Fi setup helper (uses BLE/SoftAP). Part of their provisioning apps
    espressif/network_provisioning
    espressif/esp_insights              ; Espressif’s cloud diagnostics/analytics
    espressif/esp_diag_data_store
    espressif/esp_diagnostics

    espressif/cbor                      ; Espressif’s Concise Binary Object Representation
                                        ;   esentially binary data serialization
    espressif/qrcode                    ; Espressif’s QR code
    espressif/esp-sr                    ; Espressif’s voice recognition library
    espressif/libsodium                 ; Espressif’s cryptography library
    espressif/esp-modbus                ; Espressif’s modBus protocol implementation
    chmorgan/esp-libhelix-mp3           ; Espressif’s MP3 audio decoding
    espressif/esp32-camera              ; Espressif’s driver for ESP32-CAM and other cameras

custom_sdkconfig =
    ; Optimization level
    ;CONFIG_COMPILER_OPTIMIZATION_DEBUG=y    ; -Og flag to CFLAGS
    ;CONFIG_COMPILER_OPTIMIZATION_SIZE=y     ; -Os flag to CFLAGS (-Oz with Clang)
    '# CONFIG_COMPILER_OPTIMIZATION_SIZE is not set'     ; -Os flag to CFLAGS (-Oz with Clang)
    CONFIG_COMPILER_OPTIMIZATION_PERF=y     ; -O2 flag to CFLAGS
    ;CONFIG_COMPILER_OPTIMIZATION_NONE=y     ; -O0 flag to CFLAGS

    CONFIG_ESP_WIFI_IRAM_OPT=y
    CONFIG_ESP_WIFI_EXTRA_IRAM_OPT=y
    CONFIG_ESP_WIFI_RX_IRAM_OPT=y
    CONFIG_LWIP_IRAM_OPTIMIZATION=y
    ;CONFIG_LWIP_EXTRA_IRAM_OPTIMIZATION=y

    CONFIG_LWIP_MAX_SOCKETS=8
    CONFIG_ESP_WIFI_STATIC_TX_BUFFER=y
    CONFIG_ESP_WIFI_STATIC_TX_BUFFER_NUM=16
    CONFIG_ESP_WIFI_CACHE_TX_BUFFER_NUM=8
    CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=16
    CONFIG_ESP_WIFI_STATIC_RX_MGMT_BUFFER=y
    CONFIG_ESP_WIFI_RX_MGMT_BUF_NUM_DEF=5
    ;CONFIG_ESP_WIFI_CSI_ENABLED=y
    '# CONFIG_ESP_WIFI_CSI_ENABLED is not set'
    CONFIG_ESP_WIFI_AMPDU_TX_ENABLED=y
    ;'# CONFIG_ESP_WIFI_AMPDU_TX_ENABLED is not set'
    CONFIG_ESP_WIFI_TX_BA_WIN=4
    CONFIG_ESP_WIFI_AMPDU_RX_ENABLED=y
    ;'# CONFIG_ESP_WIFI_AMPDU_RX_ENABLED is not set'
    CONFIG_ESP_WIFI_RX_BA_WIN=8
    ;'# CONFIG_ESP_WIFI_AMSDU_TX_ENABLED is not set'

    CONFIG_LWIP_TCP_HIGH_SPEED_RETRANSMISSION=y
    CONFIG_LWIP_TCP_MAXRTX=3
    CONFIG_LWIP_TCP_SYNMAXRTX=3
    CONFIG_LWIP_TCP_MSS=1440
    CONFIG_LWIP_TCP_SND_BUF_DEFAULT=8192
    CONFIG_LWIP_TCP_WND_DEFAULT=8192
    CONFIG_LWIP_TCP_TMR_INTERVAL=50
    CONFIG_LWIP_TCP_MSL=1000
    CONFIG_LWIP_TCP_FIN_WAIT_TIMEOUT=1000
    CONFIG_LWIP_TCP_RECVMBOX_SIZE=8
    CONFIG_LWIP_TCP_ACCEPTMBOX_SIZE=6
    CONFIG_LWIP_TCP_QUEUE_OOSEQ=y
    ;'# CONFIG_LWIP_TCP_QUEUE_OOSEQ is not set'
    CONFIG_LWIP_TCP_OOSEQ_TIMEOUT=3
    CONFIG_LWIP_TCP_OOSEQ_MAX_PBUFS=4
    CONFIG_LWIP_TCP_SACK_OUT=y
    ;'# CONFIG_LWIP_TCP_SACK_OUT is not set'
    CONFIG_LWIP_TCP_OVERSIZE_MSS=y
    ;'# CONFIG_LWIP_TCP_OVERSIZE_DISABLE is not set'
    CONFIG_LWIP_TCP_RTO_TIME=300

    CONFIG_LWIP_SO_REUSE=y
    '# CONFIG_LWIP_SO_REUSE_RXTOALL is not set'
    CONFIG_LWIP_SO_RCVBUF=y

    ; Set flash settings (for some reason it autodetects some imaginary amount of ram otherwise)
    ;CONFIG_ESPTOOLPY_FLASH_MODE_AUTO_DETECT
    ;CONFIG_ESPTOOLPY_FLASHMODE_DIO
    CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
    ;CONFIG_ESPTOOLPY_FLASHSIZE_16MB
    ;CONFIG_ESPTOOLPY_FLASHSIZE="16MB"
    CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
    CONFIG_ESPTOOLPY_FLASHSIZE="4MB"

    ; Disable non essential components
    '# CONFIG_BT_ENABLED is not set'
    ;CONFIG_BT_NIMBLE_ENABLED
    ;CONFIG_BT_CONTROLLER_ENABLED
    ;CONFIG_BT_CONTROLLER_DISABLED=y
    ;CONFIG_ETH_USE_ESP32_EMAC
    ;CONFIG_ETH_PHY_INTERFACE_RMII
    ;CONFIG_ETH_RMII_CLK_INPUT
    ;CONFIG_ETH_RMII_CLK_IN_GPIO

    ; Enable FREERTOS tracing capabilities
    CONFIG_FREERTOS_USE_TRACE_FACILITY=y
    CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=y
    CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID=y
    CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=y

lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	bblanchon/ArduinoJson
	fastled/FastLED
	robtillaart/AS5600@^0.6.6
    https://github.com/MarlinFirmware/TMCStepper
extra_scripts = 
	post:check_fs_size.py
